// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	blockchain.proto

It has these top-level messages:
	Block
	AddBlockRequest
	AddBlockResponse
	GetBlockchainRequest
	GetBlockchainResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Index     int64  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Hash      string `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	PrevHash  string `protobuf:"bytes,4,opt,name=prevHash" json:"prevHash,omitempty"`
	Data      string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Block) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

func (m *Block) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AddBlockRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *AddBlockRequest) Reset()                    { *m = AddBlockRequest{} }
func (m *AddBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*AddBlockRequest) ProtoMessage()               {}
func (*AddBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddBlockRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AddBlockResponse struct {
}

func (m *AddBlockResponse) Reset()                    { *m = AddBlockResponse{} }
func (m *AddBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*AddBlockResponse) ProtoMessage()               {}
func (*AddBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetBlockchainRequest struct {
}

func (m *GetBlockchainRequest) Reset()                    { *m = GetBlockchainRequest{} }
func (m *GetBlockchainRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockchainRequest) ProtoMessage()               {}
func (*GetBlockchainRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetBlockchainResponse struct {
	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *GetBlockchainResponse) Reset()                    { *m = GetBlockchainResponse{} }
func (m *GetBlockchainResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockchainResponse) ProtoMessage()               {}
func (*GetBlockchainResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetBlockchainResponse) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "api.Block")
	proto.RegisterType((*AddBlockRequest)(nil), "api.AddBlockRequest")
	proto.RegisterType((*AddBlockResponse)(nil), "api.AddBlockResponse")
	proto.RegisterType((*GetBlockchainRequest)(nil), "api.GetBlockchainRequest")
	proto.RegisterType((*GetBlockchainResponse)(nil), "api.GetBlockchainResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Blockchain service

type BlockchainClient interface {
	AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error)
	GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error) {
	out := new(AddBlockResponse)
	err := grpc.Invoke(ctx, "/api.Blockchain/AddBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error) {
	out := new(GetBlockchainResponse)
	err := grpc.Invoke(ctx, "/api.Blockchain/GetBlockchain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blockchain service

type BlockchainServer interface {
	AddBlock(context.Context, *AddBlockRequest) (*AddBlockResponse, error)
	GetBlockchain(context.Context, *GetBlockchainRequest) (*GetBlockchainResponse, error)
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Blockchain/AddBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).AddBlock(ctx, req.(*AddBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetBlockchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlockchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Blockchain/GetBlockchain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlockchain(ctx, req.(*GetBlockchainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlock",
			Handler:    _Blockchain_AddBlock_Handler,
		},
		{
			MethodName: "GetBlockchain",
			Handler:    _Blockchain_GetBlockchain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain.proto",
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x69, 0xaa, 0xf6, 0x21, 0x44, 0x75, 0x4a, 0x91, 0x89, 0x18, 0x22, 0x4b, 0x48,
	0x99, 0x32, 0x94, 0x09, 0x31, 0xd1, 0x85, 0xce, 0xf9, 0x07, 0x6e, 0x63, 0x29, 0x16, 0x34, 0x31,
	0xb5, 0x41, 0x6c, 0xfc, 0x06, 0xfe, 0x31, 0x8a, 0x93, 0x26, 0x34, 0xea, 0x76, 0xf7, 0xde, 0x77,
	0xe7, 0x67, 0x1b, 0x8b, 0xed, 0x7b, 0xbd, 0x7b, 0xdb, 0x95, 0x52, 0x57, 0x99, 0x39, 0xd4, 0xae,
	0xa6, 0x40, 0x1a, 0x2d, 0x7e, 0x10, 0xae, 0x1b, 0x83, 0x22, 0x84, 0xba, 0x2a, 0xd4, 0x37, 0x67,
	0x09, 0x4b, 0x83, 0xbc, 0x6d, 0xe8, 0x1e, 0x73, 0xa7, 0xf7, 0xca, 0x3a, 0xb9, 0x37, 0xfc, 0xd2,
	0x3b, 0x83, 0x40, 0x84, 0x49, 0x29, 0x6d, 0xc9, 0x83, 0x84, 0xa5, 0xf3, 0xdc, 0xd7, 0x14, 0x63,
	0x66, 0x0e, 0xea, 0x6b, 0xd3, 0xe8, 0x13, 0xaf, 0xf7, 0x7d, 0xc3, 0x17, 0xd2, 0x49, 0x1e, 0xb6,
	0x7c, 0x53, 0x8b, 0x07, 0xdc, 0xbc, 0x14, 0x85, 0xcf, 0x90, 0xab, 0x8f, 0x4f, 0x65, 0x5d, 0x8f,
	0xb1, 0x7f, 0x18, 0x61, 0x31, 0x60, 0xd6, 0xd4, 0x95, 0x55, 0xe2, 0x16, 0xd1, 0xab, 0x72, 0xeb,
	0xfe, 0x5e, 0xdd, 0xbc, 0x78, 0xc6, 0x72, 0xa4, 0xb7, 0x03, 0x24, 0x30, 0xf5, 0xaf, 0x60, 0x39,
	0x4b, 0x82, 0xf4, 0x6a, 0x85, 0x4c, 0x1a, 0x9d, 0xb5, 0x4b, 0x3b, 0x67, 0xf5, 0xcb, 0x80, 0x61,
	0x94, 0x9e, 0x30, 0x3b, 0x9e, 0x4b, 0x91, 0xc7, 0x47, 0x69, 0xe3, 0xe5, 0x48, 0xed, 0xc2, 0x5d,
	0xd0, 0x06, 0xd7, 0x27, 0x31, 0xe8, 0xce, 0x93, 0xe7, 0x22, 0xc7, 0xf1, 0x39, 0xeb, 0xb8, 0x69,
	0x3b, 0xf5, 0x1f, 0xf6, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x07, 0xb1, 0x0c, 0xc4, 0x01,
	0x00, 0x00,
}
